[package]
authors = ["Thespragg <alistair@aspragg.me>"]
edition = "2018"
name = "jupiter_crypt"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rand]
version = "0.3.0"
